import subprocess
import sys

# Map scripts to expected output files
SCRIPT_OUTPUTS = {
    "scripts/figures.py": [
        "docs/figures/quadrants.png",
        "docs/figures/grade_distribution.png",
    ],
}


def get_staged_files():
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-only"], capture_output=True, text=True
    )
    return set(result.stdout.strip().splitlines())


def main():
    """Check if files generated by scripts are staged in git if the script is staged."""
    staged_files = get_staged_files()
    failed = False

    for script, outputs in SCRIPT_OUTPUTS.items():
        if script in staged_files:
            for output in outputs:
                if output not in staged_files:
                    print(
                        f"❌ {output} not staged but {script} was modified. Please update and commit the figure."
                    )
                    failed = True

    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
