name: Check Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  template:
    name: Check Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check template
        run: uv run cookiecutter . -f --no-input

      - name: Print generated folder structure
        run: tree -a project_name

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            latex
            latex-bin
            xetex
            fontspec
            graphics
            tools
            pgf
            xcolor
            inputenc
            microtype
            titlesec
            parskip
            pgfplots
            listings
            siunitx
            cleveref
            textcomp
            caption
            subcaption
            csquotes
            biblatex
            booktabs
            float
            blindtext

      - name: Compile project plan
        run: |
          cd project_name/project_plan
          pdflatex -interaction=nonstopmode -halt-on-error main.tex
          bibtex main
          pdflatex -interaction=nonstopmode -halt-on-error main.tex
          pdflatex -interaction=nonstopmode -halt-on-error main.tex

      - name: Check pdf was generated
        run: |
          cd project_name/project_plan
          if [ ! -f main.pdf ]; then
            echo "PDF file not found!"
            exit 1
          fi

      - name: Upload project plan
        uses: actions/upload-artifact@v4
        with:
          name: project_plan
          path: project_name/project_plan/main.pdf

      - name: Compile thesis
        run: |
          cd project_name/thesis
          pdflatex -interaction=nonstopmode -halt-on-error main.tex
          biber main
          pdflatex -interaction=nonstopmode -halt-on-error main.tex
          pdflatex -interaction=nonstopmode -halt-on-error main.tex

      - name: Check pdf was generated
        run: |
          cd project_name/thesis
          if [ ! -f main.pdf ]; then
            echo "PDF file not found!"
            exit 1
          fi

      - name: Upload thesis
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: project_name/thesis/main.pdf

      - name: Check devcontainer
        run: |
          cd project_name
          npx @devcontainers/cli build --workspace-folder .
          npx @devcontainers/cli up --workspace-folder .
        env:
          TERM: xterm
