name: Check Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  template:
    name: Check Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check template
        run: uv run cookiecutter . -f --no-input

      - name: Print generated folder structure
        run: tree -a project_name
