name: Check Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  template:
    name: Check Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check template
        run: uv run cookiecutter . -f --no-input

      - name: Print generated folder structure
        run: tree -a project_name

      - name: Install necessary packages
        run: |
          sudo tlmgr install pgf

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-basic
            latex
            latex-bin
            xetex
            fontspec
            graphics
            tools
            xcolor

      - name: Compile project plan
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error project_name/project_plan/main.tex
          bibtex project_name/thesis/main
          pdflatex -interaction=nonstopmode -halt-on-error project_name/project_plan/main.tex
          pdflatex -interaction=nonstopmode -halt-on-error project_name/project_plan/main.tex

      - name: Compile thesis
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error project_name/thesis/main.tex
          bibtex project_name/thesis/main
          pdflatex -interaction=nonstopmode -halt-on-error project_name/thesis/main.tex
          pdflatex -interaction=nonstopmode -halt-on-error project_name/thesis/main.tex
